# Generated by Django 3.0.6 on 2020-05-18 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
